# generated by datamodel-codegen:
#   filename:  lab.schema.json

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

type Id = str


type Hash = str


type Version = str


type Vec3Item = float


type Vec3 = list[Vec3Item]


type QuaternionItem = float


type Quaternion = list[QuaternionItem]


type TransformItem = float


type Transform = tuple[
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    TransformItem,
    Literal[0],
    Literal[0],
    Literal[0],
    Literal[1],
]


class Units(TypedDict):
    length: Literal['m']
    temperature: Literal['K']
    angle: Literal['rad']
    time: Literal['s']
    world_frame: Literal['east-up-south']
    matrix_layout: Literal['row-major']


class Artifact(TypedDict):
    id: Id
    sha256: Hash
    byte_length: int
    media_type: Literal[
        'model/gltf-binary', 'application/json', 'application/x-npy', 'image/png'
    ]


type ShapeItem = int


class ArrayArtifact(TypedDict):
    artifact: Artifact
    dtype: Literal['uint8', 'uint16', 'uint32', 'float32', 'float64', 'bool']
    shape: list[ShapeItem]
    units: Literal['1', 'pixel', 'm', 's', 'K', 'W/m2/sr']
    frame: Literal[
        'image-top-left',
        'optical-right-down-forward',
        'lidar-forward-left-up',
        'east-up-south',
    ]


type ExtentMItem = float


class Box3(TypedDict):
    frame: Literal['east-up-south']
    center_m: Vec3
    extent_m: list[ExtentMItem]
    quaternion_xyzw: Quaternion


class Material(TypedDict):
    id: Id
    emissivity: float
    solar_absorption: float
    thermal_capacity_j_per_k: float
    area_m2: float
    convection_w_per_m2_k: float
    response_time_s: float
    opaque_rgb: bool
    opaque_ir: bool
    opaque_lidar: bool


class HeatSource(TypedDict):
    part_id: Id
    power_w: float
    coupling_fraction: float
    operating_state: Literal['off', 'idle', 'running']


class Part(TypedDict):
    id: Id
    mesh_node: str
    material_id: Id
    semantic: str


class Source(TypedDict):
    project: str
    revision: str
    sha256: Hash
    adapter_version: Version
    use_permission: str


class AssetRecord(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['AssetRecord']
    asset_id: Id
    content_sha256: Hash
    mesh: Artifact
    metadata: Artifact
    source: Source
    units: Units
    scale_m_per_source_unit: float
    T_world_from_asset: Transform
    contact_point_m: Vec3
    class_name: Literal['aircraft', 'ground_vehicle', 'ship', 'background']
    bounds: Box3
    parts: list[Part]
    materials: list[Material]
    heat_sources: list[HeatSource]
    thermal_model_version: Version


class Instance(TypedDict):
    instance_id: Id
    asset_id: Id
    asset_sha256: Hash
    T_world_from_asset: Transform
    operating_state: Literal['off', 'idle', 'running']


class Feature(TypedDict):
    id: Id
    type: Literal['canyon', 'alpine', 'islands', 'coast', 'aerodrome', 'harbor']
    center_m: Vec3
    extent_m: list[ExtentMItem]
    seed: int


class WorldSpec(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['WorldSpec']
    world_id: Id
    seed: int
    units: Units
    extent_m: list[ExtentMItem]
    origin_m: Vec3
    chunk_size_m: float
    generator_version: Version
    field_version: Version
    features: list[Feature]
    instances: list[Instance]


class Camera(TypedDict):
    frame: Literal['optical-right-down-forward']
    width_px: int
    height_px: int
    fx_px: float
    fy_px: float
    cx_px: float
    cy_px: float
    distortion: Literal['ideal-pinhole']


class Lidar(TypedDict):
    frame: Literal['lidar-forward-left-up']
    rows: int
    columns: int
    horizontal_fov_rad: float
    vertical_fov_rad: float
    return_policy: Literal['single-first-opaque']


class SensorRig(TypedDict):
    sensor_id: Id
    modality: Literal['rgb', 'ir', 'lidar']
    available: bool
    T_rig_from_sensor: Transform
    timestamp_offset_s: float
    exposure_s: float
    scan_duration_s: float
    min_range_m: float
    max_range_m: float
    camera: Camera | None
    lidar: Lidar | None
    sensor_model_version: Version


class Sensors(TypedDict):
    pass


class RigSpec(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['RigSpec']
    rig_id: Id
    calibration_version: Version
    T_world_from_rig: Transform
    sensors: list[SensorRig] | Sensors
    timing_profile: Literal['synchronized-static', 'timed-scan']


class EnvironmentSpec(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['EnvironmentSpec']
    environment_id: Id
    simulation_time_s: float
    solar_time_hour: float
    latitude_rad: float
    sun_direction_world: Vec3
    ambient_temperature_k: float
    fog_extinction_per_m: float
    rain_mm_per_h: float
    snow_mm_per_h: float
    wind_m_per_s: Vec3
    wetness: float
    parameter_set_version: Version
    thermal_history: Literal['equilibrated', 'continued']
    thermal_state: Artifact | None


class SeedChannels(TypedDict):
    world: int
    weather: int
    rgb: int
    ir: int
    lidar: int


class CapturePlan(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['CapturePlan']
    capture_id: Id
    sequence_id: Id
    world_sha256: Hash
    rig_sha256: Hash
    environment_sha256: Hash
    simulation_time_s: float
    geometry_policy: Literal['fixed-sensor-geometry']
    quality_version: Version
    seed_channels: SeedChannels
    modalities: list[Literal['rgb', 'ir', 'lidar']]


class CaptureRequest(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['CaptureRequest']
    world: WorldSpec
    rig: RigSpec
    environment: EnvironmentSpec
    plan: CapturePlan


class CaptureJobError(TypedDict):
    code: Literal[
        'worker_crash',
        'worker_timeout',
        'worker_context_lost',
        'worker_interrupted',
        'worker_error',
    ]
    message: str


class CaptureArtifacts(TypedDict):
    rgb: Artifact
    depth_preview: Artifact
    instance_preview: Artifact
    depth: Artifact
    instance: Artifact
    ir_preview: NotRequired[Artifact]
    ir_radiance: NotRequired[Artifact]
    ir_validity: NotRequired[Artifact]
    ir_saturation: NotRequired[Artifact]
    thermal_state: NotRequired[Artifact]
    lidar_xyz: NotRequired[Artifact]
    lidar_intensity: NotRequired[Artifact]
    lidar_beam_id: NotRequired[Artifact]
    lidar_time_offset: NotRequired[Artifact]
    lidar_validity: NotRequired[Artifact]
    lidar_class_ref: NotRequired[Artifact]
    lidar_beam_status: NotRequired[Artifact]
    lidar_ideal_range: NotRequired[Artifact]
    lidar_ideal_instance: NotRequired[Artifact]
    lidar_ideal_class: NotRequired[Artifact]
    lidar_range_preview: NotRequired[Artifact]
    lidar_cloud_preview: NotRequired[Artifact]
    lidar_topdown_preview: NotRequired[Artifact]
    metadata: Artifact


type PreviewScaleItem = float


class IrCalibration(TypedDict):
    response_version: Literal['lwir-8-14um.v1']
    band_um: tuple[Literal[8], Literal[14]]
    radiance_units: Literal['W/m2/sr']
    noise_sigma_w_per_m2_sr: float
    saturation_w_per_m2_sr: float
    thermal_model_version: Literal['thermal-surface.v1']
    thermal_state_version: Literal['thermal-state.v1']
    preview_palette: Literal['iron-v1']
    preview_scale: tuple[PreviewScaleItem, PreviewScaleItem]
    palette_applies_to_raw: Literal[False]


class LidarClassEntry(TypedDict):
    id: int
    name: Literal[
        'unclassified',
        'terrain',
        'pavement',
        'marking',
        'building',
        'vegetation',
        'rock',
        'fence',
        'aircraft',
        'ground_vehicle',
        'ship',
        'water',
    ]
    color: str


class StatusCodes(TypedDict):
    no_return: Literal[0]
    surface: Literal[1]
    receiver_dropout: Literal[2]


class Response(TypedDict):
    range_sigma_m: float
    intensity_sigma: float
    dropout_probability: float
    intensity_model: Literal['synthetic-incidence-exponential.v1']


class LidarCalibration(TypedDict):
    version: Literal['lidar-first-return.v1']
    sensor_id: Id
    frame: Literal['lidar-forward-left-up']
    rows: int
    columns: int
    horizontal_fov_rad: float
    vertical_fov_rad: float
    scan_duration_s: float
    timestamp_offset_s: float
    min_range_m: float
    max_range_m: float
    T_world_from_rig: Transform
    T_rig_from_sensor: Transform
    beam_order: Literal['row-major; rows top-to-bottom, columns left-to-right']
    class_schema_version: NotRequired[Literal['lidar-semantic.v1']]
    class_table: NotRequired[list[LidarClassEntry]]
    cloud_preview_projection: NotRequired[Literal['rgb-camera-perspective']]
    topdown_preview_projection: NotRequired[Literal['lidar-sensor-overhead']]
    status_codes: StatusCodes
    response: Response


type ResidentChunk = str


class CaptureResult(TypedDict):
    protocol: Literal['capture-worker.v1']
    capture_id: Id
    sequence_id: Id
    tick_s: float
    width: int
    height: int
    renderer: str
    device: str
    browser_channel: str
    elapsed_ms: float
    render_elapsed_ms: float
    node_rss_bytes: int
    browser_heap_bytes: int | None
    gpu_memory_bytes: int | None
    resident_chunks: list[ResidentChunk]
    instance_ids: dict[Id, int]
    ir_calibration: IrCalibration | None
    lidar_calibration: LidarCalibration | None
    lidar_point_count: int
    artifacts: CaptureArtifacts


class CaptureJob(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['CaptureJob']
    job_id: Id
    capture_id: Id
    state: Literal[
        'queued', 'running', 'cancelling', 'cancelled', 'succeeded', 'failed'
    ]
    progress: float
    result: CaptureResult | None
    error: CaptureJobError | None
    created_at: str
    updated_at: str


class Unavailable(TypedDict):
    status: Literal['unavailable']
    reason: Literal['not_implemented', 'disabled', 'hardware_failure']
    message: str


class Image(ArrayArtifact):
    dtype: Literal['uint8']
    units: Literal['1']
    frame: Literal['image-top-left']
    shape: tuple[ShapeItem, ShapeItem, Literal[3]]


class ValidityMask(ArrayArtifact):
    dtype: Literal['bool']
    units: Literal['1']
    frame: Literal['image-top-left']
    shape: tuple[ShapeItem, ShapeItem]


class RgbData(TypedDict):
    image: Image
    validity_mask: ValidityMask
    transfer_function: Literal['srgb']
    exposure_s: float


class Radiance(ArrayArtifact):
    dtype: Literal['float32']
    units: Literal['W/m2/sr']
    frame: Literal['image-top-left']
    shape: tuple[ShapeItem, ShapeItem]


class ValidityMask1(ArrayArtifact):
    dtype: Literal['bool']
    units: Literal['1']
    frame: Literal['image-top-left']
    shape: tuple[ShapeItem, ShapeItem]


class SaturationMask(ArrayArtifact):
    dtype: Literal['bool']
    units: Literal['1']
    frame: Literal['image-top-left']
    shape: tuple[ShapeItem, ShapeItem]


type BandUmItem = float


class IrData(TypedDict):
    radiance: Radiance
    validity_mask: ValidityMask1
    saturation_mask: SaturationMask
    band_um: list[BandUmItem]
    response_version: Version


class Xyz(ArrayArtifact):
    dtype: Literal['float32']
    units: Literal['m']
    frame: Literal['lidar-forward-left-up']
    shape: tuple[ShapeItem, Literal[3]]


class Intensity(ArrayArtifact):
    dtype: Literal['float32']
    units: Literal['1']
    frame: Literal['lidar-forward-left-up']
    shape: tuple[ShapeItem]


class BeamId(ArrayArtifact):
    dtype: Literal['uint32']
    units: Literal['1']
    frame: Literal['lidar-forward-left-up']
    shape: tuple[ShapeItem]


class TimeOffset(ArrayArtifact):
    dtype: Literal['float32']
    units: Literal['s']
    frame: Literal['lidar-forward-left-up']
    shape: tuple[ShapeItem]


class Validity(ArrayArtifact):
    dtype: Literal['bool']
    units: Literal['1']
    frame: Literal['lidar-forward-left-up']
    shape: tuple[ShapeItem]


class BeamTable(ArrayArtifact):
    dtype: Literal['uint8']
    units: Literal['1']
    frame: Literal['lidar-forward-left-up']
    shape: tuple[ShapeItem]


class LidarData(TypedDict):
    xyz: Xyz
    intensity: Intensity
    beam_id: BeamId
    time_offset: TimeOffset
    validity: Validity
    beam_table: BeamTable


class RgbObservation1(TypedDict):
    status: Literal['available']
    timestamp_s: float
    health: Literal['ok', 'degraded']
    sensor_id: Id
    sensor_model_version: Version
    data: RgbData


type RgbObservation = Unavailable | RgbObservation1


class IrObservation1(TypedDict):
    status: Literal['available']
    timestamp_s: float
    health: Literal['ok', 'degraded']
    sensor_id: Id
    sensor_model_version: Version
    data: IrData


type IrObservation = Unavailable | IrObservation1


class LidarObservation1(TypedDict):
    status: Literal['available']
    timestamp_s: float
    health: Literal['ok', 'degraded']
    sensor_id: Id
    sensor_model_version: Version
    data: LidarData


type LidarObservation = Unavailable | LidarObservation1


class ObservationBundle(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['ObservationBundle']
    capture_id: Id
    sequence_id: Id
    rig: RigSpec
    rgb: RgbObservation
    ir: IrObservation
    lidar: LidarObservation


type VisibleBoxXyxyItem = int


class VisibleCamera(TypedDict):
    mask: ArrayArtifact
    visible_box_xyxy: list[VisibleBoxXyxyItem] | None
    visible_pixels: int
    isolated_projected_pixels: int
    visible_fraction: float | None
    truncated: bool


class ObjectAnnotation(TypedDict):
    instance_id: Id
    class_id: int
    box_3d: Box3
    rgb: VisibleCamera
    ir: VisibleCamera
    lidar_ideal_hits: int
    lidar_surface_hits: int
    eligible: bool
    ignore_reason: Literal['out_of_frustum', 'fully_occluded', 'small_fragment'] | None


class AnnotationBundle(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['AnnotationBundle']
    capture_id: Id
    class_map_version: Version
    visibility_policy_version: Version
    objects: list[ObjectAnnotation]


class SurfaceTemperaturesKItem(TypedDict):
    part_id: Id
    temperature_k: float


class ObjectTruth(TypedDict):
    instance: Instance
    velocity_m_per_s: Vec3
    surface_temperatures_k: list[SurfaceTemperaturesKItem]


class TruthBundle(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['TruthBundle']
    capture_id: Id
    world: WorldSpec
    actual_rig: RigSpec
    environment: EnvironmentSpec
    objects: list[ObjectTruth]
    clean_intermediates: list[Artifact]
    corruption_masks: list[ArrayArtifact]


class CaptureEntry(TypedDict):
    capture_id: Id
    sequence_id: Id
    group_id: Id
    split: Literal['train', 'validation', 'test']
    observation: Artifact
    annotations: Artifact
    truth: Artifact | None


class Provenance(TypedDict):
    source_revision: str
    world_sha256: Hash
    asset_hashes: list[Hash]
    config_sha256: Hash
    sensor_version: Version
    generator_version: Version
    toolchain: str
    seed: int


class ClassMapItem(TypedDict):
    id: int
    name: str


class Counts(TypedDict):
    train: int
    validation: int
    test: int


class DatasetManifest(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['DatasetManifest']
    dataset_id: Id
    created_utc: str
    provenance: Provenance
    class_map: list[ClassMapItem]
    class_map_version: Version
    captures: list[CaptureEntry]
    files: list[ArrayArtifact]
    counts: Counts


type PositionVarianceM2Item = float


type RoutingItem = float


class Detection(TypedDict):
    prediction_id: Id
    class_id: int
    box_3d: Box3
    score: float
    position_variance_m2: list[PositionVarianceM2Item]
    observation_supported: bool
    routing: list[RoutingItem] | None


class PredictionBundle(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['PredictionBundle']
    capture_id: Id
    checkpoint_id: Id
    checkpoint_sha256: Hash
    latency_ms: float
    detections: list[Detection]
    state: Artifact | None


class Health(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['Health']
    status: Literal['ok']
    service: Literal['yulab-backend']
    service_version: Literal['0.1.0']


class Capability(TypedDict):
    available: bool
    reason: Literal['not_implemented', 'no_checkpoint', 'device_unavailable'] | None


class Sensors1(TypedDict):
    rgb: Capability
    ir: Capability
    lidar: Capability


class Services(TypedDict):
    worlds: Capability
    capture: Capability
    datasets: Capability
    training: Capability
    inference: Capability


class Capabilities(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['Capabilities']
    service_version: Literal['0.1.0']
    contracts_version: Literal['lab.v1']
    capture_renderer: str | None
    device: str | None
    sensors: Sensors1
    services: Services
    checkpoints: list[Id]


class Detail(TypedDict):
    path: str
    message: str


class ApiError(TypedDict):
    schema_version: Literal['lab.v1']
    kind: Literal['ApiError']
    code: Literal[
        'not_found', 'method_not_allowed', 'validation_error', 'internal_error'
    ]
    message: str
    request_id: Id
    job_id: Id | None
    details: list[Detail]


type LabPayload = AssetRecord | WorldSpec | RigSpec | EnvironmentSpec | CapturePlan | CaptureRequest | CaptureJob | ObservationBundle | AnnotationBundle | TruthBundle | DatasetManifest | PredictionBundle | Health | Capabilities | ApiError
