import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowRight, Box, Check, ChevronDown, CircleHelp, Compass, Download, Expand, Eye, FileBox, FolderHeart, Grid2X2, Hand, Info, Layers3, Leaf, LoaderCircle, Maximize, Mountain, Move3D, Plus, Minus, RotateCcw, Save, Shuffle, SlidersHorizontal, Sparkles, Sun, Trees, Waves, X } from 'lucide-react';
import TerrainViewport, { type SceneStats, type ViewportHandle } from './TerrainViewport';
import { DEFAULT_CONFIG, PRESETS, makePreviews, type TerrainConfig } from './terrain';

type SavedPreset = { name: string; config: TerrainConfig; date: string };
function Logo({ small = false }: { small?: boolean }) { return <svg width={small ? 23 : 35} height={small ? 23 : 35} viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M4 30 16 8l7 13 5-8 9 17H4Z" stroke="currentColor" strokeWidth="2.3" strokeLinejoin="round"/><path d="m10 30 9-15M20 30l7-12M16 23l6 7" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round"/></svg>; }
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) { return <button role="switch" aria-checked={checked} aria-label={label} onClick={onChange} className={`toggle ${checked ? 'on' : ''}`}><span /></button>; }
function Range({ label, value, onChange, suffix = '', min = 0, max = 100, display, hint }: { label: string; value: number; onChange: (value: number) => void; suffix?: string; min?: number; max?: number; display?: string; hint?: string }) { return <label className="range-control"><span className="range-label"><span>{label}{hint && <span className="help-dot" title={hint}>?</span>}</span><span className="range-value">{display ?? value}<span>{suffix}</span></span></span><input type="range" aria-label={label} min={min} max={max} value={value} onChange={e => onChange(Number(e.target.value))} style={{ '--range-progress': `${(value - min) / (max - min) * 100}%` } as React.CSSProperties} /></label>; }
function Section({ title, icon, children, defaultOpen = true }: { title: string; icon: React.ReactNode; children: React.ReactNode; defaultOpen?: boolean }) { const [open, setOpen] = useState(defaultOpen); return <section className="control-section"><button className="section-heading" onClick={() => setOpen(!open)} aria-expanded={open}><span>{icon}{title}</span><ChevronDown size={14} className={open ? '' : 'closed'} /></button>{open && <div className="section-body">{children}</div>}</section>; }

export default function App() {
  const [draft, setDraft] = useState<TerrainConfig>(DEFAULT_CONFIG);
  const [config, setConfig] = useState<TerrainConfig>(DEFAULT_CONFIG);
  const [tab, setTab] = useState('terrain');
  const [autoUpdate, setAutoUpdate] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [stats, setStats] = useState<SceneStats>({ triangles: 0, vertices: 0, resolution: 0, time: 0 });
  const [fps, setFps] = useState(60);
  const [wireframe, setWireframe] = useState(false);
  const [grid, setGrid] = useState(false);
  const [autoRotate, setAutoRotate] = useState(false);
  const [tool, setTool] = useState('orbit');
  const [previews, setPreviews] = useState<Record<string, string>>({});
  const [exportOpen, setExportOpen] = useState(false);
  const [cameraOpen, setCameraOpen] = useState(false);
  const [modal, setModal] = useState<'help' | 'save' | 'presets' | null>(null);
  const [toast, setToast] = useState('');
  const [exporting, setExporting] = useState(false);
  const [presetName, setPresetName] = useState('My canyon landscape');
  const [saved, setSaved] = useState<SavedPreset[]>(() => { try { return JSON.parse(localStorage.getItem('strata-presets') || '[]'); } catch { return []; } });
  const viewport = useRef<ViewportHandle>(null);
  const viewportPanel = useRef<HTMLDivElement>(null);
  const update = <K extends keyof TerrainConfig>(key: K, value: TerrainConfig[K]) => setDraft(d => ({ ...d, [key]: value }));
  const notify = (message: string) => setToast(message);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3500); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!autoUpdate) return; const timer = setTimeout(() => setConfig(draft), 220); return () => clearTimeout(timer); }, [draft, autoUpdate]);
  useEffect(() => { const timer = setTimeout(() => { try { setPreviews(makePreviews()); } catch { /* The main viewport provides a WebGL availability message. */ } }, 500); return () => clearTimeout(timer); }, []);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === 'Escape') { setModal(null); setExportOpen(false); setCameraOpen(false); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const receiveStats = useCallback((next: SceneStats) => { setStats(next); setGenerating(false); }, []);
  const generate = () => { setGenerating(true); setTimeout(() => { setConfig({ ...draft }); notify('Your new landscape is ready to explore.'); }, 80); };
  const randomize = () => { const next = { ...draft, seed: Math.floor(Math.random() * 899999) + 10000 }; setDraft(next); if (!autoUpdate) notify('Seed randomized. Generate to apply your changes.'); };
  const applyPreset = (next: TerrainConfig) => { setDraft({ ...next }); setConfig({ ...next }); setModal(null); };
  const exportTerrain = async (type: 'glb' | 'obj' | 'png') => { setExportOpen(false); setExporting(true); try { await viewport.current?.exportFile(type); notify(`${type.toUpperCase()} exported. A little world, ready to go.`); } catch { notify('Export failed. Please try again once your terrain is ready.'); } finally { setExporting(false); } };
  const savePreset = () => { if (!presetName.trim()) return; const next = [...saved, { name: presetName.trim(), config: { ...config }, date: new Date().toLocaleDateString() }]; try { localStorage.setItem('strata-presets', JSON.stringify(next)); setSaved(next); setModal(null); notify('Preset saved to this browser.'); } catch { notify('Local storage is full or unavailable.'); } };
  const fullScreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await viewportPanel.current?.requestFullscreen(); } catch { notify('Fullscreen is not available in this browser.'); } };
  const selectedPreset = PRESETS.find(p => p.id === draft.preset);
  const dirty = JSON.stringify(config) !== JSON.stringify(draft);

  return <div className="app-shell">
    <header className="app-header">
      <a href="./" className="brand" aria-label="Strata home"><span className="brand-mark"><Logo /></span><span className="wordmark">strata<span className="brand-period">.</span></span><span className="beta-badge">BETA</span></a>
      <div className="header-divider" /><span className="header-descriptor">A playground for worlds.</span>
      <nav className="header-actions"><button className="text-button presets-link" onClick={() => setModal('presets')}><FolderHeart size={16} />My presets{saved.length > 0 && <span className="count-badge">{saved.length}</span>}</button><button className="text-button guide-button" onClick={() => setModal('help')}><CircleHelp size={16} /><span>Quick guide</span></button><span className="action-divider"/><div className="export-wrapper"><button className="primary-button export-button" onClick={() => setExportOpen(!exportOpen)} aria-expanded={exportOpen}>{exporting ? <LoaderCircle size={16} className="spin"/> : <Download size={16}/>}<span>{exporting ? 'Exporting…' : 'Export terrain'}</span><ChevronDown size={14}/></button>{exportOpen && <><button className="dropdown-dismiss" aria-label="Close export menu" onClick={() => setExportOpen(false)}/><div className="dropdown export-menu"><div className="dropdown-label">TAKE YOUR WORLD WITH YOU</div><button onClick={() => exportTerrain('glb')}><FileBox size={18}/><span><strong>3D model <em>.glb</em></strong><small>Mesh, colors, and vegetation</small></span><ArrowDownToLine size={14}/></button><button onClick={() => exportTerrain('obj')}><Box size={18}/><span><strong>Wavefront <em>.obj</em></strong><small>Universal 3D geometry</small></span><ArrowDownToLine size={14}/></button><button onClick={() => exportTerrain('png')}><Eye size={18}/><span><strong>Viewport image <em>.png</em></strong><small>A snapshot of your current view</small></span><ArrowDownToLine size={14}/></button></div></>}</div></nav>
    </header>

    <main className="workspace">
      <div className="workspace-intro"><div><div className="eyebrow"><span className="tiny-line"/> THE WORLD IS YOURS TO SHAPE</div><h1>Small polygons. <span>Endless possibilities.</span></h1></div><div className="intro-note"><Box size={15}/><span>Real 3D. Naturally different.</span></div></div>
      <div className="studio-layout">
        <aside className="controls-panel">
          <div className="panel-title"><span><SlidersHorizontal size={17}/>Terrain settings</span><button className="icon-button reset-settings" title="Reset all settings" aria-label="Reset all settings" onClick={() => { applyPreset(DEFAULT_CONFIG); notify('Back to the beginning. Settings reset.'); }}><RotateCcw size={15}/></button></div>
          <div className="control-tabs"><button className={tab === 'terrain' ? 'active' : ''} onClick={() => setTab('terrain')}><Mountain size={15}/>Terrain</button><button className={tab === 'style' ? 'active' : ''} onClick={() => setTab('style')}><Sun size={15}/>Appearance</button></div>
          <div className="controls-scroll">
            {tab === 'terrain' ? <>
              <div className="seed-control"><div className="small-label"><span>World seed</span><span className="help-dot" title="The same seed and settings always create the same landscape.">?</span></div><div className="seed-input"><span className="hash-mark">#</span><input aria-label="World seed" type="number" min="0" max="999999999" value={draft.seed} onChange={e => update('seed', Math.min(999999999, Math.max(0, Number(e.target.value))))}/><button title="Randomize seed" aria-label="Randomize seed" onClick={randomize}><Shuffle size={16}/></button></div></div>
              <Section title="Base terrain" icon={<Mountain size={16}/>}><Range label="Terrain scale" value={draft.scale} min={16} max={128} suffix="m" onChange={v => update('scale', v)}/><Range label="Elevation" value={draft.height} min={10} max={85} suffix="m" onChange={v => update('height', v)}/><Range label="Roughness" value={draft.roughness} display={(draft.roughness / 100).toFixed(2)} hint="Adds multi-scale noise throughout the 3D density field." onChange={v => update('roughness', v)}/></Section>
              <Section title="3D formations" icon={<Layers3 size={16}/>}><div className="feature-row"><span><ArchIcon/>Natural arches</span><Toggle checked={draft.arches} label="Natural arches" onChange={() => update('arches', !draft.arches)}/></div><div className="feature-row"><span><OverhangIcon/>Overhangs</span><Toggle checked={draft.overhangs} label="Overhangs" onChange={() => update('overhangs', !draft.overhangs)}/></div><div className="feature-row"><span><TunnelIcon/>Tunnels & caves</span><Toggle checked={draft.tunnels} label="Tunnels and caves" onChange={() => update('tunnels', !draft.tunnels)}/></div><div className="strength-range"><Range label="Formation strength" value={draft.strength} display={(draft.strength / 100).toFixed(2)} onChange={v => update('strength', v)}/></div></Section>
              <Section title="Mesh detail" icon={<Box size={16}/>}><div className="segmented detail-selector">{[{ name: 'Low', value: 20 }, { name: 'Medium', value: 48 }, { name: 'High', value: 85 }].map(d => <button key={d.name} className={draft.detail === d.value ? 'selected' : ''} onClick={() => update('detail', d.value)}>{d.name}</button>)}</div><p className="detail-hint">Fewer faces. More character.</p></Section>
            </> : <>
              <Section title="Color palette" icon={<Sun size={16}/>}><p className="style-description">Give your world its own atmosphere.</p><div className="palette-list">{[{ id: 'earth', name: 'Earth & sage', colors: ['#b88e65', '#d1b38d', '#7e8b54', '#425b43'] }, { id: 'alpine', name: 'Alpine stone', colors: ['#8d9992', '#b6beb4', '#788d68', '#e6e5d7'] }, { id: 'moss', name: 'Moss & mist', colors: ['#8e9275', '#abb08e', '#6e8c64', '#47624c'] }, { id: 'coast', name: 'Coastal calm', colors: ['#bdab8d', '#d8cbb0', '#8daa79', '#8dbab5'] }, { id: 'desert', name: 'Desert warmth', colors: ['#bc7551', '#d69f75', '#bca36e', '#a15f42'] }].map(p => <button key={p.id} className={`palette-option ${draft.palette === p.id ? 'active' : ''}`} onClick={() => update('palette', p.id)}><span className="color-swatches">{p.colors.map(c => <i key={c} style={{ background: c }}/>)}</span><span>{p.name}</span>{draft.palette === p.id && <Check size={14}/>}</button>)}</div></Section>
              <Section title="Life & atmosphere" icon={<Leaf size={16}/>}><div className="feature-row"><span><Trees size={17}/>Vegetation</span><Toggle checked={draft.vegetation} label="Vegetation" onChange={() => update('vegetation', !draft.vegetation)}/></div><p className="style-description under-toggle">Scatter low-poly pines across the landscape.</p><div className="feature-row"><span><Waves size={17}/>Water level</span><Toggle checked={draft.water} label="Water level" onChange={() => update('water', !draft.water)}/></div><p className="style-description under-toggle">Add a calm, translucent shoreline.</p></Section>
              <Section title="Viewport" icon={<Eye size={16}/>}><div className="feature-row"><span>Slow orbit</span><Toggle checked={autoRotate} label="Slow orbit" onChange={() => setAutoRotate(!autoRotate)}/></div><div className="feature-row"><span>Ground grid</span><Toggle checked={grid} label="Ground grid" onChange={() => setGrid(!grid)}/></div></Section>
            </>}
          </div>
          <div className="generate-area"><button className="primary-button generate-button" onClick={generate} disabled={generating}>{generating ? <LoaderCircle size={17} className="spin"/> : <Sparkles size={17}/>}<span>{generating ? 'Shaping your world…' : 'Generate terrain'}</span><span className="generate-arrow"><ArrowRight size={17}/></span></button><div className="auto-update"><span><span className={`status-dot ${autoUpdate ? '' : 'paused'}`}/>{dirty && !autoUpdate ? 'Unapplied changes' : 'Auto-update'}</span><Toggle checked={autoUpdate} label="Auto-update" onChange={() => setAutoUpdate(!autoUpdate)}/></div></div>
        </aside>

        <div className="main-column">
          <div className="viewport-panel" ref={viewportPanel}>
            <div className="viewport-topbar"><div className="scene-title"><span className="scene-dot"/><span>Untitled landscape</span><span className="scene-divider">/</span><span className="scene-preset">{selectedPreset?.name}</span></div><div className="viewport-top-actions"><div className="shading-switch"><button className={!wireframe ? 'active' : ''} onClick={() => setWireframe(false)}><Box size={13}/><span>Shaded</span></button><button className={wireframe ? 'active' : ''} onClick={() => setWireframe(true)}><Grid2X2 size={13}/><span>Wireframe</span></button></div><button className="icon-button fullscreen-button" title="Toggle fullscreen" aria-label="Toggle fullscreen" onClick={fullScreen}><Expand size={16}/></button></div></div>
            <div className="viewport-content">
              <TerrainViewport ref={viewport} config={config} wireframe={wireframe} grid={grid} autoRotate={autoRotate} tool={tool} onStats={receiveStats} onFps={setFps}/>
              <div className="live-badge"><span className="status-dot"/>{generating ? 'GENERATING' : 'LIVE PREVIEW'}</div>
              <div className="camera-control"><button onClick={() => setCameraOpen(!cameraOpen)} aria-expanded={cameraOpen}><Box size={14}/><span>Perspective</span><ChevronDown size={12}/></button>{cameraOpen && <div className="dropdown camera-menu"><button onClick={() => { viewport.current?.reset(); setCameraOpen(false); }}>Perspective view</button><button onClick={() => { viewport.current?.top(); setCameraOpen(false); }}>Top-down view</button><button onClick={() => { setAutoRotate(!autoRotate); setCameraOpen(false); }}>{autoRotate ? 'Stop' : 'Start'} slow orbit</button></div>}</div>
              <div className="viewport-tools"><button className={tool === 'orbit' ? 'active' : ''} title="Orbit terrain" aria-label="Orbit terrain" onClick={() => setTool('orbit')}><Move3D size={18}/></button><button className={tool === 'pan' ? 'active' : ''} title="Pan terrain" aria-label="Pan terrain" onClick={() => setTool('pan')}><Hand size={17}/></button><span/><button title="Zoom in" aria-label="Zoom in" onClick={() => viewport.current?.zoom(.85)}><Plus size={18}/></button><button title="Zoom out" aria-label="Zoom out" onClick={() => viewport.current?.zoom(1.17)}><Minus size={18}/></button><span/><button title="Reset camera" aria-label="Reset camera" onClick={() => viewport.current?.reset()}><Maximize size={17}/></button><button className={grid ? 'active' : ''} title="Toggle ground grid" aria-label="Toggle ground grid" onClick={() => setGrid(!grid)}><Grid2X2 size={16}/></button></div>
              <div className="viewport-bottom-left"><span className="terrain-tag"><Logo small/>LOW POLY, HIGH POSSIBILITY.</span><div className="interaction-hints"><span><MouseIcon/>Drag to orbit</span><i/><span>Scroll to zoom</span><i/><span>Right-drag to pan</span></div></div>
              <div className="axis-widget" aria-hidden="true"><svg width="66" height="67" viewBox="0 0 66 67"><path d="M31 38V12" stroke="#89957b" strokeWidth="1.5"/><path d="m31 38 23 13" stroke="#b77961" strokeWidth="1.5"/><path d="M31 38 10 51" stroke="#7c94a0" strokeWidth="1.5"/><circle cx="31" cy="38" r="3" fill="#ada99b"/><circle cx="31" cy="11" r="8" fill="#dfe4d5"/><circle cx="55" cy="52" r="8" fill="#e5d5ca"/><circle cx="9" cy="52" r="8" fill="#d6e0e2"/><text x="31" y="14" textAnchor="middle" fill="#647054">Y</text><text x="55" y="55" textAnchor="middle" fill="#a26751">X</text><text x="9" y="55" textAnchor="middle" fill="#667e8c">Z</text></svg></div>
            </div>
            <div className="viewport-status"><span className="volumetric-label"><Box size={13}/>Volumetric terrain<span className="status-separator"/><span>Marching cubes</span></span><div className="mesh-stats"><span><strong>{stats.vertices.toLocaleString()}</strong> vertices</span><span><strong>{stats.triangles.toLocaleString()}</strong> faces</span><span className="fps-stat"><span className="status-dot"/>{fps} FPS</span></div></div>
          </div>

          <section className="presets-section"><div className="presets-heading"><div><h2>A starting point for your imagination</h2><span>Pick a preset. Make it your own.</span></div><button className="text-button save-preset-button" onClick={() => setModal('save')}><Plus size={15}/>Save preset</button></div><div className="preset-grid">{PRESETS.map(p => <button key={p.id} className={`preset-card ${draft.preset === p.id ? 'selected' : ''}`} onClick={() => applyPreset(p.config)}><div className={`preset-image preset-${p.id}`}>{previews[p.id] ? <img src={previews[p.id]} alt={`Low-poly ${p.name.toLowerCase()} landscape`}/> : <Mountain size={35}/>}<span className="preset-selection">{draft.preset === p.id ? <Check size={12}/> : <ArrowRight size={12}/>}</span></div><div className="preset-info"><strong>{p.name}</strong><span>{p.description}</span></div></button>)}</div></section>
        </div>
      </div>
      <footer className="workspace-footer"><span><Box size={13}/>Built in three dimensions. Not just a heightmap.<button onClick={() => setModal('help')}>Meet the engine<ArrowRight size={12}/></button></span><span className="footer-right">A little noise. A whole new world.<span className="footer-star">✳</span></span></footer>
    </main>
    {toast && <div className="toast" role="status"><span><Check size={15}/></span>{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={14}/></button></div>}
    {modal && <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setModal(null); }}><section className={`modal ${modal === 'help' ? 'help-modal' : ''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close icon-button" onClick={() => setModal(null)} aria-label="Close dialog"><X size={19}/></button>
      {modal === 'help' && <><div className="modal-brand"><Logo/></div><span className="eyebrow">A LITTLE GUIDE TO BIG IDEAS</span><h2 id="modal-title">Not just another heightmap.</h2><p className="modal-intro">Strata makes little worlds with real depth. Every terrain is a fully three-dimensional, low-poly mesh—ready to explore or take into your next project.</p><div className="guide-grid"><div><Box size={20}/><h3>Volume, not elevation</h3><p>A seeded 3D density field is surfaced with marching cubes. Subtractive volumes carve genuine arches and through-tunnels; additive volumes create unsupported overhangs.</p></div><div><SlidersHorizontal size={20}/><h3>A world in your hands</h3><p>Start with a preset, change the seed, and play with the controls. Auto-update previews every change. Switch it off to adjust several settings before generating.</p></div><div><Compass size={20}/><h3>Take a look around</h3><p>Drag to orbit, scroll to zoom, and right-drag to pan. Inspect the triangles in Wireframe or reset your view with the frame tool.</p></div><div><Download size={20}/><h3>Make something with it</h3><p>Export a GLB with colors and vegetation, an OBJ mesh, or a PNG of your current view. Presets are stored privately in this browser.</p></div></div><div className="guide-note"><Info size={16}/><span>Formation controls shape Canyon and Coastal presets. Alpine peaks and Floating islands use their own volumetric structures.</span></div><button className="primary-button modal-primary" onClick={() => setModal(null)}>Let’s make a world<ArrowRight size={16}/></button></>}
      {modal === 'save' && <><div className="modal-brand"><FolderHeart size={28}/></div><h2 id="modal-title">Keep this little world.</h2><p className="modal-intro">Save the current generated terrain settings so you can return to them anytime.</p><label className="save-label">Preset name<input autoFocus value={presetName} maxLength={48} onChange={e => setPresetName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') savePreset(); }} placeholder="Give your landscape a name"/></label><div className="save-summary"><Mountain size={17}/><span>{PRESETS.find(p => p.id === config.preset)?.name}</span><span>Seed #{config.seed}</span></div><p className="local-note">Saved locally in this browser. No account needed.</p><button className="primary-button modal-primary" disabled={!presetName.trim()} onClick={savePreset}><Save size={16}/>Save preset</button></>}
      {modal === 'presets' && <><div className="modal-brand"><FolderHeart size={28}/></div><h2 id="modal-title">Your collection of worlds.</h2><p className="modal-intro">Little experiments worth coming back to.</p>{saved.length === 0 ? <div className="empty-presets"><Mountain size={42}/><h3>A whole world of potential.</h3><p>Save your first landscape using “Save preset” below the viewport.</p><button className="primary-button" onClick={() => setModal('save')}><Plus size={15}/>Save this landscape</button></div> : <div className="saved-list">{saved.map((p, i) => <div className="saved-item" key={`${p.name}-${i}`}><button onClick={() => { applyPreset(p.config); notify(`Loaded “${p.name}”.`); }}><span className="saved-thumb">{previews[p.config.preset] ? <img src={previews[p.config.preset]} alt=""/> : <Mountain/>}</span><span><strong>{p.name}</strong><small>#{p.config.seed} · {p.date}</small></span><ArrowRight size={16}/></button><button className="icon-button delete-preset" aria-label={`Delete ${p.name}`} title="Delete preset" onClick={() => { const next = saved.filter((_, index) => i !== index); try { localStorage.setItem('strata-presets', JSON.stringify(next)); setSaved(next); } catch { notify('Could not update local storage.'); } }}><X size={15}/></button></div>)}</div>}</>}
    </section></div>}
  </div>;
}
function ArchIcon() { return <svg width="17" height="17" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.35"><path d="M3 17V10a7 7 0 0 1 14 0v7h-4v-7a3 3 0 0 0-6 0v7H3Z"/><path d="M2 17h6m4 0h6"/></svg>; }
function OverhangIcon() { return <svg width="17" height="17" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.35" strokeLinejoin="round"><path d="M3 17V5l5-2 9 2-1 5-7 1v6H3Z"/><path d="m3 8 6 3M8 3l2 5 7-3"/></svg>; }
function TunnelIcon() { return <svg width="17" height="17" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.35" strokeLinejoin="round"><path d="m2 17 2-9 5-4 6 2 3 11h-6v-5a3 3 0 0 0-6 0v5H2Z"/><path d="m9 4 2 3 4-1"/></svg>; }
function MouseIcon() { return <svg width="11" height="14" viewBox="0 0 12 16" fill="none" stroke="currentColor"><rect x="2" y="1" width="8" height="13" rx="4"/><path d="M6 3v3"/></svg>; }
